## Some numpy demonstrations

Below some illustrations of the use of numpy. First we show the difference with lists: numpy arrays can hold only one type of data and multiplication works differently.

In [1]:
# Multiplication of a mixed list
aMixedList = [12, 5.4, 'five point four', 2 + 2j]
print(2*aMixedList)
for i in range(len(aMixedList)):
    aMixedList[i] = 2*aMixedList[i]
print(aMixedList)

[12, 5.4, 'five point four', (2+2j), 12, 5.4, 'five point four', (2+2j)]
[24, 10.8, 'five point fourfive point four', (4+4j)]


In [2]:
# Multiplication of a numpy array
import numpy as np
aNumpyArray = np.array((1,2,3))
print(2*aNumpyArray)
for i in range(len(aNumpyArray)):
    aNumpyArray[i] = 2*aNumpyArray[i]
print(aNumpyArray)


[2 4 6]
[2 4 6]


Because all data is of the same type, less checking is needed and operations are (much) faster. We demonstrate this with the two cells below.

In [3]:
# Computing the electron density within a certain radius
from math import sqrt, exp, pi

Z = 8.
n=10**7
rmax=0.5
total_density = 0.0
volume = rmax / n
for i in range(n):
    r = rmax * i / n
    func_2s = 1./(4.*sqrt(2*pi)) * Z**(3./2.) * (2-Z*r) * exp(-Z*r/2)
    dens_2s = 4 * pi * (r * func_2s )**2
    total_density += dens_2s * volume

print ("Total density within a radius {} is {:9.6f}".format(rmax,total_density))

Total density within a radius 0.5 is  0.175796


In [5]:
# Computing the electron density within a certain radius with numpy
import numpy as np

Z = 8.
n=10**7
rmax=0.5
volume = rmax / n

prefactor= 1./(4.* np.sqrt(2*np.pi)) * Z**(3./2.)
r = np.linspace(0.0, rmax, num=n)
func_2s = prefactor * (2-Z*r) * np.exp(-Z*r/2)
dens_2s = 4 * np.pi * (r * func_2s)**2
print ('Total density within a radius of {} Bohr is {:9.6f}'.format(rmax,dens_2s.sum()*volume))


Total density within a radius of 0.5 Bohr is  0.175796


In [6]:
print(np.linspace(1,3,11)[10])

3.0


We can also use numpy arrays as *arguments* in a function

In [7]:
def SumAndProduct(x,y):
    sum = x+y
    product = x*y
    return sum, product

x = np.arange(1,4,1)
y = np.arange(4,1,-1)
print(x,y)
s, p = SumAndProduct(x,y)
print(s,p)

[1 2 3] [4 3 2]
[5 5 5] [4 6 6]


or have numpy arrays as a *return value* of a function.

In [8]:
import numpy as np

def sinc(x):
    mask = np.abs(x) >= 1.e-15
    y = np.ones_like(x)
    y[mask] = np.sin(x[mask]) / x[mask]
    return y

x = np.array(np.pi*np.arange(-1,1.2,0.2))
print(x)
print(sinc(x))

[-3.14159265e+00 -2.51327412e+00 -1.88495559e+00 -1.25663706e+00
 -6.28318531e-01 -6.97573700e-16  6.28318531e-01  1.25663706e+00
  1.88495559e+00  2.51327412e+00  3.14159265e+00]
[3.89817183e-17 2.33872321e-01 5.04551152e-01 7.56826729e-01
 9.35489284e-01 1.00000000e+00 9.35489284e-01 7.56826729e-01
 5.04551152e-01 2.33872321e-01 4.63055676e-16]
